---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-environment
spec:
  params:
    - name: target-environment
      description: the target environment
      default: "I did not get one"
  results:
    - name: extracted-environment-value
      description: The extracted value
  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)
  steps:
    - name: echo-some-stuff
      image: ibmcom/pipeline-base-image:2.6
      env:
        - name: ENVIRONMENT
          value: $(params.target-environment)
      command: ["/bin/bash", "-c"]
      args:
        - |
          #!/bin/bash
          echo "******"
          echo $ENVIRONMENT
          echo "******"
      volumeMounts:
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: cd-config-volume
      configMap:
        name: $(params.config-map-name)
